frr version 9.1
frr defaults traditional
hostname R2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface eth1
 description Link to R1
 ip address 10.0.12.2/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20

interface eth2
 description Link to R3
 ip address 10.0.23.1/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20

interface lo
 ip address 2.2.2.2/32
 ip ospf area 0

router ospf
 ospf router-id 2.2.2.2
 network 0.0.0.0/0 area 0

line vty
