frr version 9.1
frr defaults traditional
hostname R1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface eth1
 description Link to R2
 ip address 10.0.12.1/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20

interface eth2
 description Link to R3
 ip address 10.0.13.1/30
 ip ospf area 0
 ip ospf hello-interval 5
 ip ospf dead-interval 20

interface eth3
 description Link to PC1
 ip address 192.168.1.1/24
 ip ospf area 0

interface lo
 ip address 1.1.1.1/32
 ip ospf area 0

router ospf
 ospf router-id 1.1.1.1
 network 0.0.0.0/0 area 0
 passive-interface eth3

line vty
